services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - todoapp-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - todoapp-network
    depends_on:
      - db

  db:
    build: ./database
    networks:
      - todoapp-network

networks:
  todoapp-network:
