services:
  frontend:
    build: ./todoapp-client
    ports:
      - "3000:3000"
    networks:
      - todoapp-network

  backend:
    build: ./todoapp-api
    ports:
      - "8080:8080"
    networks:
      - todoapp-network
    depends_on:
      - db

  db:
    build: ./PostgreSQL
    networks:
      - todoapp-network

networks:
  todoapp-network:
