services:
  todoapp-client:
    build: ./todoapp-client
    ports:
      - "3000:3000"
    networks:
      - todoapp-network

  todoapp-api:
    build: ./todoapp-api
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PW=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - GO_ENV=dev
    ports:
      - "8080:8080"
    networks:
      - todoapp-network
    depends_on:
      - db

  db:
    build: ./PostgreSQL
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - todoapp-network

networks:
  todoapp-network:

volumes:
  postgres-data:
