services:
  todoapp-client:
    build: ./todoapp-client
    ports:
      - "3000:3000"
    networks:
      - todoapp-network

  todoapp-api:
    build: ./todoapp-api
    ports:
      - "8080:8080"
    networks:
      - todoapp-network
    depends_on:
      - db

  db:
    build: ./PostgreSQL
    ports:
      - "5432:5432"
    networks:
      - todoapp-network

networks:
  todoapp-network:
