services:
  todoapp-client:
    build: ./todoapp-client
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:3000"
    networks:
      - todoapp-network
    volumes:
      - ./todoapp-client:/todoapp-client
      - /todoapp-client/node_modules

  todoapp-api:
    build: ./todoapp-api
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PW=${POSTGRES_PW}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - CLIENT_URL=${CLIENT_URL}
    ports:
      - "8080:8080"
    networks:
      - todoapp-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./todoapp-api:/todoapp-api

  db:
    image: postgres:14.15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - todoapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.14
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
    networks:
      - todoapp-network
    depends_on:
      db:
        condition: service_healthy

networks:
  todoapp-network:

volumes:
  postgres-data:
  pgadmin-data:
